service: shopping-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1
  memorySize: 128
  timeout: 30

functions:
  api:
    handler: server/index.app
    events:
      - http:
          path: /{proxy+}
          method: ANY
