#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd frontend && npm run format
cd ../backend && npm run format
cd ../frontend && npm run build && cp -r ./build/ ../backend/server/build/
cd ..
git add -A .