name: Frontend
on:
  workflow_dispatch:
  pull_request:
    branches: master
    paths:
      - "frontend/**"

env:
  API_URL: ${{secrets.API_URL}}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: install dependencies
        run: cd frontend && npm i
      - name: Test
        run: cd frontend && npm run test
  Build:
    needs: Test
    runs-on: ubuntu-latest
    outputs:
      dist-file-name: ${{steps.publish.outputs.build_folder_name}}
    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: install dependencies
        run: cd frontend && npm i
      - name: make env file
        run: cd frontend && echo "API_URL=${{env.API_URL}}" > .env && cat .env
      - name: Build
        run: cd frontend && npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: ./frontend/build
      - name: Publishing dist file name
        id: publish
        run: echo 'build_folder_name=bundle' >> $GITHUB_OUTPUT
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{needs.Build.outputs.dist-file-name}}
      - name: Output content
        run: ls -l
