name: PR
on:
  pull_request:
    branches: master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: install dependencies
        run: cd frontend && npm i
      - name: Test
        run: cd frontend && npm run test
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: ./build
